<font size="5">
    
   This notebook will be a function that plots the partial and complex partial Jacobian Matrix
   $$ $$
   $$ $$
   
    
$$ J_{k} = [m_{pq} \bar g_{q} \delta^{j}_{p}] [pq] = 1...N_{bl}(p<q)     $$

$$ $$

$$ J_{k}^{*} = [g_{p} m_{pq} \delta^{j}_{q}] [pq] = 1...N_{bl}(p<q)      $$
$$ $$

where <br>
<br>
$\delta_{p}^{j}$ is a way of 
$[pq]$ represents the row <br>
g represents the gain  <br>
m is the sky coherency <br>


</font>






In [1]:
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from hera_cal.io import HERAData, HERACal
import itertools
from IPython.display import clear_output

In [3]:
#is there visibility data i can get from HERA?
#probably in the UVFITS file for sure

#If i can get visibilties in antenna numbers, I think I could create some partial Jacobians at the very least
file = '/lustre/aoc/projects/hera/H1C_IDR2/2458102/zen.2458102.44615.HH.uvh5'
hd = HERAData(file)

In [69]:
n_ant = len(hd.antenna_numbers) #number of antennas

baselines = n_ant * ( (n_ant - 1) / (2)  )  #also thought of as 'visibilities?'
print("number of baselines based on pyuvdata: {}".format(hd.Nbls))
print('number of baselines based on n_ants: {}'.format(baselines))
print('number of antennas is {}'.format(n_ant))


number of baselines based on pyuvdata: 1378
number of baselines based on n_ants: 1326.0
number of antennas is 52


(1326, 52)

In [181]:
#Partial Jacobian is in the shape of N_ant and N_bl, where baseeline is calculated above

def jacobian(n_ant):
    """ This function will create a simple Jacobian filled with 1's at non-zero places"""
    
    ant_pair = list(itertools.combinations(range(1,n_ant + 1) , 2)) #antenna pairs in array in (ant1,ant2) format
    baselines = int(n_ant * ((n_ant - 1) / 2)) #number of baselines or pairs
    jacobian = np.zeros((baselines,n_ant)) #partial jacobian
    cjacobian = np.zeros((baselines,n_ant)) #partial complex jacobian
    for i in range(baselines): #loop through baselines
    
        jacobian[i][ant_pair[i][0]-1] = 1 #regular jacobian
        cjacobian[i][ant_pair[i][1]-1] = 1 #complex jacobian
        
        conjacobian = np.conjugate(jacobian.T)
        concjacobian = np.conjugate(cjacobian.T)
        
    print('There are {} antennas, {} baselines in this array'.format(n_ant,baselines))
    print(jacobian)
    print(cjacobian)
    print(conjacobian)
    print(concjacobian)

In [182]:
jacobian(3)

There are 3 antennas, 3 baselines in this array
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[1. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 1.]]
